version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  urlshortener-app:
    build: .
    container_name: urlshortener-container
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - mysql

volumes:
  mysql_data:
